version: "2"

issues:
  fix: true

linters:
  enable:
    - gocyclo
    - godot
    - govet
    - revive
    - whitespace
    - misspell

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
        path: _test\.go

  settings:
    godot:
      exclude:
        - "^ @[A-Za-z]+ "

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gofumpt:
      extra-rules: true
    gocyclo:
      min-complexity: 15

  exclusions:
    generated: lax
