default_stages: [commit]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    # Waiting for new release, see https://github.com/alessandrojcm/commitlint-pre-commit-hook/issues/152
    rev: 46ad8d10517771202384ef846ec4a5aa17e6ad26
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy
      - id: golangci-lint
        args:
          - "--timeout=5m"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
