# Get frontend files from current version
FROM ghcr.io/envelope-zero/frontend:3.3.1 as frontend

FROM scratch
WORKDIR /
COPY --from=frontend /usr/share/nginx/html /public

COPY standalone /standalone
ENTRYPOINT ["/standalone"]
