name: "go test"
description: "runs go tests"

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3.1.0

    - name: Set up go
      uses: actions/setup-go@v3.3.1
      with:
        # renovate: go-version
        go-version: 1.18.4

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install -y gcc libgtk-3-dev libayatana-appindicator3-dev

    - name: Run go tests
      shell: bash
      run: |
        make frontend
        go test ./... -race -covermode=atomic
