name: test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          # renovate: go-version
          go-version: 1.26.4

      - name: Run go tests
        shell: bash
        run: |
          make frontend
          go test ./... -race -covermode=atomic

      # This builds the binary and starts it. If it does not exit within 3 seconds, consider it
      # successful
      - name: Verify binary works
        shell: bash
        run: |
          make build
          timeout 3 ./standalone || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
