name: test & release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.1.0

      - name: go test
        uses: ./.github/actions/go-test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.19.2

      - name: Extract frontend files
        run: make frontend

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          install-only: true

      - name: Run GoReleaser
        run: |
          sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev
          goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
