name: test & tag

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          # renovate: go-version
          go-version: 1.22.2

      - name: Run go tests
        shell: bash
        run: |
          make frontend
          go test ./... -race -covermode=atomic

      # This builds the binary and starts it. If it does not exit within 3 seconds, consider it
      # successful
      - name: Verify binary works
        shell: bash
        run: |
          make build
          timeout 3 ./standalone || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

  tag:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0
          token: ${{ secrets.EZ_BOT_TOKEN }}

      - name: Install svu
        run: |
          # renovate: datasource=github-releases depName=caarlos0/svu
          export SVU_VERSION="v1.12.0"
          curl -Lo ./svu.tar.gz "https://github.com/caarlos0/svu/releases/download/${SVU_VERSION}/svu_${SVU_VERSION#v}_linux_amd64.tar.gz"
          tar -C "$HOME" -xzf svu.tar.gz
          rm svu.tar.gz

      - name: Tag new version
        run: |
          if [ $(git tag -l "$(~/svu next)") ]; then
            echo "Tag already exists, no release necessary"
          else
            echo "Tagging new version"
            git tag "$(~/svu next)"
            git push --tags
          fi
